package forms;

import DatabaseConnection.MyConnection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mayur
 */
public class ForgotPasswordForm extends javax.swing.JFrame {

    /**
     * Creates new form Forgot Password
     */
    public ForgotPasswordForm() {
        initComponents();

        // center the form
        this.setLocationRelativeTo(null);

        // create a yellow border for the jpanel_title
        // 0 border in the top
        Border jpanel_title_border = BorderFactory.createMatteBorder(0, 1, 1, 1, Color.yellow);
        // set the border to the jPanel_title
        jPanel_title.setBorder(jpanel_title_border);

        // create an orange border for the global panel
        Border glob_panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.orange);
        jPanel1.setBorder(glob_panel_border);

        // create a black border for the close & minimize jlables
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Minimize.setBorder(label_border);
        jLabel_Close.setBorder(label_border);

        // create a border for the create acconut jlabel
        Border label_forgot_password_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel_ForgotPasswordTitle.setBorder(label_forgot_password_border);

        // create border for the username and password field
        Border field_border = BorderFactory.createMatteBorder(1, 5, 1, 1, Color.white);
        jTextField_Petname.setBorder(field_border);
        jPasswordField_NewPassword.setBorder(field_border);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_Petname = new javax.swing.JTextField();
        jPasswordField_NewPassword = new javax.swing.JPasswordField();
        jButton_ConfirmButton = new javax.swing.JButton();
        jLabel_AlreadyLogin = new javax.swing.JLabel();
        jLabel1_Petname_Question = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jPasswordField_ConfirmNewPassword = new javax.swing.JPasswordField();
        jCheckBox_ShowPassword = new javax.swing.JCheckBox();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jPanel_title = new javax.swing.JPanel();
        jLabel_ForgotPasswordTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(77, 77, 77));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTextField_Petname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Petname.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Petname.setText("Enter your pet name");
        jTextField_Petname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_PetnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_PetnameFocusLost(evt);
            }
        });
        jTextField_Petname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PetnameKeyPressed(evt);
            }
        });

        jPasswordField_NewPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_NewPassword.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_NewPassword.setText("password");
        jPasswordField_NewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_NewPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_NewPasswordFocusLost(evt);
            }
        });
        jPasswordField_NewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_NewPasswordKeyPressed(evt);
            }
        });

        jButton_ConfirmButton.setBackground(new java.awt.Color(0, 84, 140));
        jButton_ConfirmButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jButton_ConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ConfirmButton.setText("CONFIRM");
        jButton_ConfirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ConfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ConfirmButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ConfirmButtonMouseExited(evt);
            }
        });
        jButton_ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmButtonActionPerformed(evt);
            }
        });
        jButton_ConfirmButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ConfirmButtonKeyPressed(evt);
            }
        });

        jLabel_AlreadyLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_AlreadyLogin.setForeground(new java.awt.Color(0, 204, 0));
        jLabel_AlreadyLogin.setText(">> Already Have an Account? Login!");
        jLabel_AlreadyLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_AlreadyLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AlreadyLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_AlreadyLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_AlreadyLoginMouseExited(evt);
            }
        });

        jLabel1_Petname_Question.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1_Petname_Question.setText("What is your pet name ?");

        jTextField_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Username.setText("Enter your username");
        jTextField_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusLost(evt);
            }
        });
        jTextField_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_UsernameKeyPressed(evt);
            }
        });

        jPasswordField_ConfirmNewPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_ConfirmNewPassword.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_ConfirmNewPassword.setText("password");
        jPasswordField_ConfirmNewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_ConfirmNewPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_ConfirmNewPasswordFocusLost(evt);
            }
        });
        jPasswordField_ConfirmNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_ConfirmNewPasswordKeyPressed(evt);
            }
        });

        jCheckBox_ShowPassword.setText("Show Passwords");
        jCheckBox_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ShowPasswordActionPerformed(evt);
            }
        });
        jCheckBox_ShowPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox_ShowPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Petname, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_ConfirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_ShowPassword)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1_Petname_Question))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton_ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel_AlreadyLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_Petname_Question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Petname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField_ConfirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_ShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel_AlreadyLogin)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel_Minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Minimize.setText(" -");
        jLabel_Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseExited(evt);
            }
        });

        jLabel_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Close.setText(" X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });

        jPanel_title.setBackground(new java.awt.Color(0, 204, 0));

        jLabel_ForgotPasswordTitle.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        jLabel_ForgotPasswordTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ForgotPasswordTitle.setText("Forgot Password");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel_ForgotPasswordTitle)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ForgotPasswordTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Minimize)
                            .addComponent(jLabel_Close)))
                    .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_Minimize.setBorder(label_border);
        jLabel_Minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_MinimizeMouseEntered

    private void jLabel_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Minimize.setBorder(label_border);
        jLabel_Minimize.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_MinimizeMouseExited

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_Close.setBorder(label_border);
        jLabel_Close.setForeground(Color.white);

    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(label_border);
        jLabel_Close.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jTextField_PetnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_PetnameFocusGained

//        clear the textfield on focus if the text is "enter your pet name"
        String username = jTextField_Petname.getText().trim().toLowerCase();
        if (username.equals("enter your pet name")) {
            jTextField_Petname.setText("");
            jTextField_Petname.setForeground(Color.black);
        }

    }//GEN-LAST:event_jTextField_PetnameFocusGained

    private void jTextField_PetnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_PetnameFocusLost

        String petname = jTextField_Petname.getText().trim();

        if (petname.equals("")
                || petname.toLowerCase().equals("enter your pet name")) {
            jTextField_Petname.setText("Enter your pet name");
            jTextField_Petname.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_jTextField_PetnameFocusLost

    private void jPasswordField_NewPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_NewPasswordFocusGained

//         clear the password field on focus if the text is "password"
//         get the password text
        String password = String.valueOf(jPasswordField_NewPassword.getPassword()).trim().toLowerCase();

        if (password.equals("password")) {
            jPasswordField_NewPassword.setText("");
            jPasswordField_NewPassword.setForeground(Color.black);
        }

    }//GEN-LAST:event_jPasswordField_NewPasswordFocusGained

    private void jPasswordField_NewPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_NewPasswordFocusLost

//         if the password field is equal to password or empty
//         we will set the "password" text in the field 
//         on focus lost event get the password text
        String password = String.valueOf(jPasswordField_NewPassword.getPassword()).trim().toLowerCase();

        if (password.equals("") || password.equals("password")) {
            jPasswordField_NewPassword.setText("password");
            jPasswordField_NewPassword.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_jPasswordField_NewPasswordFocusLost

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        jLabel_AlreadyLoginMouseClicked(evt);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_AlreadyLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AlreadyLoginMouseClicked

        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jLabel_AlreadyLoginMouseClicked

    private void jLabel_AlreadyLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AlreadyLoginMouseEntered

        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0, 204, 0));
        jLabel_AlreadyLogin.setBorder(label_border);

    }//GEN-LAST:event_jLabel_AlreadyLoginMouseEntered

    private void jLabel_AlreadyLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AlreadyLoginMouseExited

        Border label_forgot_password_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel_AlreadyLogin.setBorder(label_forgot_password_border);

    }//GEN-LAST:event_jLabel_AlreadyLoginMouseExited

    private void jButton_ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmButtonActionPerformed

        confirmButtonAction();

    }//GEN-LAST:event_jButton_ConfirmButtonActionPerformed

//   method to confirm new reset password
    private void confirmEnteredButtonAction(KeyEvent evt){
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmButtonAction();
        }
        
    }//end - confirmEnteredButtonAction() method
    
    //to update new Password by confirming
    private void confirmButtonAction() {
        String usrname = jTextField_Username.getText().trim();
        String ptname = jTextField_Petname.getText().trim();
        String newPassword = String.valueOf(jPasswordField_NewPassword.getPassword()).trim();
        String confirmNewPassword = String.valueOf(jPasswordField_ConfirmNewPassword.getPassword()).trim();

        if (!isUsernameAndPetnameValid(usrname, ptname)) {
            JOptionPane.showMessageDialog(null, "Incorrect username/petname", "Confirm Username",
                    JOptionPane.CANCEL_OPTION);
        } else if (!newPassword.equals(confirmNewPassword)) {
            JOptionPane.showMessageDialog(null, "Entered Password Doesn't Match", "Confirm Password",
                    JOptionPane.CANCEL_OPTION);
        } else {

            String query = "UPDATE users SET password = ? WHERE username = ?";

            final PreparedStatement st;
            Connection conn = null;

            try {
                conn = MyConnection.getConnection();
                st = conn.prepareStatement(query);
                st.setString(1, newPassword);
                st.setString(2, usrname);

                if (st.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "Password Changed Successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry couldn't updated!");
                }//end if-else
            } catch (SQLException ex) {
                Logger.getLogger(ForgotPasswordForm.class.getName()).log(Level.SEVERE, null, ex);
            } finally {

                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ForgotPasswordForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            } // end - try catch finally
        }// end - if else
    }//end - confirmButtonAction method

// create a function to check if the entered username already exists in the database
    public boolean isUsernameAndPetnameValid(String username, String petname) {

        Connection conn = null;
        final PreparedStatement st;
        ResultSet rs = null;
        boolean userExist = false;
        String query = "SELECT username,petname FROM users WHERE username = ? AND petname = ?"; //

        try {
            conn = MyConnection.getConnection();
            st = conn.prepareStatement(query);
            st.setString(1, username);
            st.setString(2, petname);
            rs = st.executeQuery();
            if (rs.next()) {
                userExist = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (conn != null) {
                    conn.close();

                }
            } catch (SQLException ex) {
                Logger.getLogger(ForgotPasswordForm.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } //end - try catch finally

        return userExist;
    }//end - isUsernameAndPetnameValid() method


    private void jButton_ConfirmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ConfirmButtonMouseExited
        // set jbutton background
        jButton_ConfirmButton.setBackground(new Color(0, 84, 104));

    }//GEN-LAST:event_jButton_ConfirmButtonMouseExited

    private void jButton_ConfirmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ConfirmButtonMouseEntered
        // set jbutton background
        jButton_ConfirmButton.setBackground(new Color(0, 101, 183));

    }//GEN-LAST:event_jButton_ConfirmButtonMouseEntered

    private void jTextField_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusGained
//        clear the textfield on focus if the text is "enter your username"
        String username = jTextField_Username.getText().trim().toLowerCase();
        if (username.equals("enter your username")) {
            jTextField_Username.setText("");
            jTextField_Username.setForeground(Color.black);
        }

    }//GEN-LAST:event_jTextField_UsernameFocusGained

    private void jTextField_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusLost
//         if the text field is equal to username or empty
//         we will set the "enter your username" text in the field 
//         on focus lost event
        if (jTextField_Username.getText().trim().equals("")
                || jTextField_Username.getText().trim().toLowerCase().equals("enter your username")) {
            jTextField_Username.setText("Enter your username");
            jTextField_Username.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_jTextField_UsernameFocusLost

    private void jPasswordField_ConfirmNewPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmNewPasswordFocusGained
//         clear the password field on focus if the text is "password"
//         get the password text
        String password = String.valueOf(jPasswordField_ConfirmNewPassword.getPassword()).trim().toLowerCase();
        if (password.equals("password")) {
            jPasswordField_ConfirmNewPassword.setText("");
            jPasswordField_ConfirmNewPassword.setForeground(Color.black);
        }

    }//GEN-LAST:event_jPasswordField_ConfirmNewPasswordFocusGained

    private void jPasswordField_ConfirmNewPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmNewPasswordFocusLost

//         if the password field is equal to password or empty
//         we will set the "password" text in the field 
//         on focus lost event get the password text
        String password = String.valueOf(jPasswordField_ConfirmNewPassword.getPassword()).trim().toLowerCase();

        if (password.equals("") || password.equals("password")) {
            jPasswordField_ConfirmNewPassword.setText("password");
            jPasswordField_ConfirmNewPassword.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_jPasswordField_ConfirmNewPasswordFocusLost

    private void jCheckBox_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ShowPasswordActionPerformed

        showPasswords();

    }//GEN-LAST:event_jCheckBox_ShowPasswordActionPerformed

    private void showPasswords() {
        if (jCheckBox_ShowPassword.isSelected()) {
            jPasswordField_NewPassword.setEchoChar((char) 0);
            jPasswordField_ConfirmNewPassword.setEchoChar((char) 0);
            return;
        }
        jPasswordField_NewPassword.setEchoChar('*');
        jPasswordField_ConfirmNewPassword.setEchoChar('*');
    }// end - showPasswords() method

    private void jTextField_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_UsernameKeyPressed
//        to confirm new reset password
        confirmEnteredButtonAction(evt);

    }//GEN-LAST:event_jTextField_UsernameKeyPressed

    private void jTextField_PetnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PetnameKeyPressed
//        to confirm new reset password
        confirmEnteredButtonAction(evt);

    }//GEN-LAST:event_jTextField_PetnameKeyPressed

    private void jPasswordField_NewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_NewPasswordKeyPressed
//        to confirm new reset password
        confirmEnteredButtonAction(evt);
    }//GEN-LAST:event_jPasswordField_NewPasswordKeyPressed

    private void jPasswordField_ConfirmNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmNewPasswordKeyPressed
//        to confirm new reset password
        confirmEnteredButtonAction(evt);

    }//GEN-LAST:event_jPasswordField_ConfirmNewPasswordKeyPressed

    private void jCheckBox_ShowPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox_ShowPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!jCheckBox_ShowPassword.isSelected()) {
                jCheckBox_ShowPassword.setSelected(true);
            } else {
                jCheckBox_ShowPassword.setSelected(false);
            }
        }
        showPasswords();
    }//GEN-LAST:event_jCheckBox_ShowPasswordKeyPressed

    private void jButton_ConfirmButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ConfirmButtonKeyPressed
        //        to confirm new reset password
        confirmEnteredButtonAction(evt);
    }//GEN-LAST:event_jButton_ConfirmButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ForgotPasswordForm().setVisible(true);
        });
        /*      OR
        
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginForm().setVisible(true);
//            }
//        });
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ConfirmButton;
    private javax.swing.JCheckBox jCheckBox_ShowPassword;
    private javax.swing.JLabel jLabel1_Petname_Question;
    private javax.swing.JLabel jLabel_AlreadyLogin;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_ForgotPasswordTitle;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JPasswordField jPasswordField_ConfirmNewPassword;
    private javax.swing.JPasswordField jPasswordField_NewPassword;
    private javax.swing.JTextField jTextField_Petname;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables

}// end - ForgotPasswordForm class
