package forms;

import DatabaseConnection.MyConnection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mayur
 */
public class RegisterForm extends javax.swing.JFrame {

    public RegisterForm() {
        initComponents();

        // center form
        this.setLocationRelativeTo(null);

        // create a yellow border for the jpanel_title
        // 0 border in the top
        Border jpanel_title_border = BorderFactory.createMatteBorder(0, 1, 1, 1, Color.yellow);
        // set the border to the jPanel_title
        jPanel_title.setBorder(jpanel_title_border);

        // create a black border for the close & minimize jlables
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_Close.setBorder(label_border);

        // create a border for the create acconut jlabel
        Border label_login_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel_AlreadyLogin.setBorder(label_login_border);

        // create border for the text and password fields
        Border field_border = BorderFactory.createMatteBorder(1, 5, 1, 1, Color.white);
        jTextField_Username.setBorder(field_border);
        jTextField_Fullname.setBorder(field_border);
        jTextField_Phone.setBorder(field_border);
        jPasswordField_Password.setBorder(field_border);
        jPasswordField_ConfirmPassword.setBorder(field_border);
        jTextField_Petname.setBorder(field_border);

        // create a button group for the radiobuttons
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_Male);
        bg.add(jRadioButton_Female);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_Register = new javax.swing.JButton();
        jLabel_Fullname = new javax.swing.JLabel();
        jTextField_Fullname = new javax.swing.JTextField();
        jLabel_Username = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel_Password = new javax.swing.JLabel();
        jLabel_ConfirmPassword = new javax.swing.JLabel();
        jLabel_Phone = new javax.swing.JLabel();
        jTextField_Phone = new javax.swing.JTextField();
        jLabel_Gender = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jPasswordField_ConfirmPassword = new javax.swing.JPasswordField();
        jLabel_AlreadyLogin = new javax.swing.JLabel();
        jTextField_Petname = new javax.swing.JTextField();
        jLabel_Petname = new javax.swing.JLabel();
        jCheckBox_ShowPassword = new javax.swing.JCheckBox();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jPanel_title = new javax.swing.JPanel();
        jLabel_RegisterTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jButton_Register.setBackground(new java.awt.Color(235, 47, 6));
        jButton_Register.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jButton_Register.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register.setText("Register");
        jButton_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_RegisterMouseExited(evt);
            }
        });
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });
        jButton_Register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_RegisterKeyPressed(evt);
            }
        });

        jLabel_Fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Fullname.setText("Full Name:");

        jTextField_Fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Fullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_FullnameKeyPressed(evt);
            }
        });

        jLabel_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Username.setText("Username:");

        jTextField_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_UsernameKeyPressed(evt);
            }
        });

        jLabel_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Password.setText("Password:");

        jLabel_ConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_ConfirmPassword.setText("Confirm Password:");

        jLabel_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Phone.setText("Phone:");

        jTextField_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyTyped(evt);
            }
        });

        jLabel_Gender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Gender.setText("Gender:");

        jRadioButton_Male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Male.setSelected(true);
        jRadioButton_Male.setText("Male");
        jRadioButton_Male.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton_MaleKeyPressed(evt);
            }
        });

        jRadioButton_Female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Female.setText("Female");
        jRadioButton_Female.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton_FemaleKeyPressed(evt);
            }
        });

        jPasswordField_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_PasswordKeyPressed(evt);
            }
        });

        jPasswordField_ConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_ConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_ConfirmPasswordKeyPressed(evt);
            }
        });

        jLabel_AlreadyLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_AlreadyLogin.setForeground(new java.awt.Color(0, 204, 0));
        jLabel_AlreadyLogin.setText(">> Already Have an Account? Login!");
        jLabel_AlreadyLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_AlreadyLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AlreadyLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_AlreadyLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_AlreadyLoginMouseExited(evt);
            }
        });

        jTextField_Petname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PetnameKeyPressed(evt);
            }
        });

        jLabel_Petname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Petname.setText("Petname:");

        jCheckBox_ShowPassword.setText("Show Passwords");
        jCheckBox_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ShowPasswordActionPerformed(evt);
            }
        });
        jCheckBox_ShowPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox_ShowPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_AlreadyLogin)
                .addGap(146, 146, 146))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel_Phone))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_Petname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Petname, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jLabel_Gender)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton_Male)
                            .addGap(10, 10, 10)
                            .addComponent(jRadioButton_Female)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Password)
                            .addComponent(jLabel_Username))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Username)
                            .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Fullname)
                            .addComponent(jLabel_ConfirmPassword))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_ShowPassword)
                                    .addComponent(jPasswordField_ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Fullname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Username)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Password)
                    .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ConfirmPassword)
                    .addComponent(jPasswordField_ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_ShowPassword)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Petname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Petname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Phone)
                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Gender)
                    .addComponent(jRadioButton_Male)
                    .addComponent(jRadioButton_Female))
                .addGap(18, 18, 18)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_AlreadyLogin)
                .addGap(22, 22, 22))
        );

        jLabel_minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Close.setText(" X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });

        jPanel_title.setBackground(new java.awt.Color(0, 84, 140));

        jLabel_RegisterTitle.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        jLabel_RegisterTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_RegisterTitle.setText("Register");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_RegisterTitle)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_RegisterTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_minimize)
                            .addComponent(jLabel_Close))))
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegisterMouseEntered

        // set jbutton background
        jButton_Register.setBackground(new Color(225, 20, 2));

    }//GEN-LAST:event_jButton_RegisterMouseEntered

    private void jButton_RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegisterMouseExited

        // set jbutton background
        jButton_Register.setBackground(new Color(235, 47, 6));

    }//GEN-LAST:event_jButton_RegisterMouseExited

    //function to perform a user registeration action
    private void registerButtonAction() {
        String fullname = jTextField_Fullname.getText().trim();
        String username = jTextField_Username.getText().trim();
        String password = String.valueOf(jPasswordField_Password.getPassword()).trim();
        String confirmPassword = String.valueOf(jPasswordField_ConfirmPassword.getPassword()).trim();
        String phone = jTextField_Phone.getText().trim();
        String petname = jTextField_Petname.getText().trim();
        String gender = "Male";

        if (jRadioButton_Female.isSelected()) {
            gender = "Female";
        }

        if (verifyFields()) {
            if (!checkUsername(username)) {

                Connection conn = null;
                final PreparedStatement pst;
                ResultSet rs = null;
                String query;
                query = "INSERT INTO users(username, password, fullname, mobile, gender,petname)"
                        + " VALUES (?,?,?,?,?,?)";
                try {
                    conn = MyConnection.getConnection();
                    pst = conn.prepareStatement(query);
                    pst.setString(1, username);
                    pst.setString(2, password);
                    pst.setString(3, fullname);
                    pst.setString(4, phone);
                    pst.setString(5, gender);
                    pst.setString(6, petname);

                    if (pst.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Your Account Has Been Created");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                    }//end if-else
                } catch (SQLException ex) {
                    Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
//                    JOptionPane.showMessageDialog(null,"Error occurred while connecting...\nPlease check netork connection!","Connection Error",2);
                } finally {
                    try {
                        if (rs != null) {
                            rs.close();
                        }
                        if (conn != null) {
                            conn.close();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(ForgotPasswordForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }// end - try catch finally blocks
            }//end - if checkUsername()
        }//end - if verifyFiled() 
    }//end - regiterButtonAction method

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed

        registerButtonAction();

    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);

    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked

        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_Close.setBorder(label_border);
        jLabel_Close.setForeground(Color.white);

    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(label_border);
        jLabel_Close.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jTextField_PhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyTyped

        // allow only numbers
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextField_PhoneKeyTyped

    private void jLabel_AlreadyLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AlreadyLoginMouseClicked

        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jLabel_AlreadyLoginMouseClicked

    private void jLabel_AlreadyLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AlreadyLoginMouseEntered

        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0, 204, 0));
        jLabel_AlreadyLogin.setBorder(label_border);

    }//GEN-LAST:event_jLabel_AlreadyLoginMouseEntered

    private void jLabel_AlreadyLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AlreadyLoginMouseExited

        Border label_create_accont_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel_AlreadyLogin.setBorder(label_create_accont_border);

    }//GEN-LAST:event_jLabel_AlreadyLoginMouseExited

    private void jTextField_FullnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FullnameKeyPressed
//        to register by pressing enter key
        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jTextField_FullnameKeyPressed

    private void jTextField_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_UsernameKeyPressed
//        to register by pressing enter key
        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jTextField_UsernameKeyPressed

    private void jPasswordField_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordKeyPressed
//        to register by pressing enter key
        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jPasswordField_PasswordKeyPressed

    private void jPasswordField_ConfirmPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmPasswordKeyPressed
//        to register by pressing enter key
        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jPasswordField_ConfirmPasswordKeyPressed

    private void jTextField_PetnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PetnameKeyPressed
//        to register by pressing enter key
        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jTextField_PetnameKeyPressed

    private void jTextField_PhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyPressed
//            to register by pressing enter key
        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jTextField_PhoneKeyPressed

    private void jCheckBox_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ShowPasswordActionPerformed

        showPasswords();

    }//GEN-LAST:event_jCheckBox_ShowPasswordActionPerformed

    private void jRadioButton_MaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton_MaleKeyPressed
//            to register by pressing enter key
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!jRadioButton_Male.isSelected()) {
                jRadioButton_Male.setSelected(true);
            }
//            else{
//                jRadioButton_Female.setSelected(true);
//            }
        }
        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jRadioButton_MaleKeyPressed

    private void jRadioButton_FemaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton_FemaleKeyPressed
//            to register by pressing enter key
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!jRadioButton_Female.isSelected()) {
                jRadioButton_Female.setSelected(true);
            } 
//            else{
//                jRadioButton_Male.setSelected(true);
//            }
        }
        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jRadioButton_FemaleKeyPressed

    private void jCheckBox_ShowPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox_ShowPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!jCheckBox_ShowPassword.isSelected()) {
                jCheckBox_ShowPassword.setSelected(true);
            } else {
                jCheckBox_ShowPassword.setSelected(false);
            }
        }
        showPasswords();

    }//GEN-LAST:event_jCheckBox_ShowPasswordKeyPressed

    private void jButton_RegisterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_RegisterKeyPressed

        registerEnterButtonAction(evt);

    }//GEN-LAST:event_jButton_RegisterKeyPressed

    //to show or hide the hidden password
    private void showPasswords() {

        if (jCheckBox_ShowPassword.isSelected()) {
            jPasswordField_Password.setEchoChar((char) 0);
            jPasswordField_ConfirmPassword.setEchoChar((char) 0);
            return;
        }
        jPasswordField_Password.setEchoChar('*');
        jPasswordField_ConfirmPassword.setEchoChar('*');

    }//end - showPasswords() method

//    to register by pressing enter key
    private void registerEnterButtonAction(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            registerButtonAction();
        }

    }//end - registerAnAccount() method

//    create a function to verify the empty fields  
    public boolean verifyFields() {
        String fname = jTextField_Fullname.getText().trim();
        String uname = jTextField_Username.getText().trim();
        String phone = jTextField_Phone.getText().trim();
        String password = String.valueOf(jPasswordField_Password.getPassword()).trim();
        String confirmPassword = String.valueOf(jPasswordField_ConfirmPassword.getPassword()).trim();

        // check empty fields
        if (fname.equals("") || uname.equals("") || phone.equals("")
                || password.equals("") || confirmPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty", "Empty Fields", 2);
            return false;
        } // check if the two password are equals
        else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Password Doesn't Match", "Confirm Password", 2);
            return false;
        } // if everything is ok
        else {
            return true;
        }

    }//end - verifyFields() method

//     function to check, if the entered username already exists in the database
    public boolean checkUsername(String username) {

        Connection conn = null;
        final PreparedStatement st;
        ResultSet rs = null;
        boolean username_exist = false;

        String query = "SELECT * FROM users WHERE username = ?";

        try {

            conn = MyConnection.getConnection();
            st = conn.prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();

            if (rs.next()) {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another One", "Username Failed", 2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null,"Error occurred while connecting...\nPlease check netork connection!","Connection Error",2);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ForgotPasswordForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } // end - try catch finally blocks

        return username_exist;

    }//end - checkUsername() method

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterForm().setVisible(true);
        });

        /*      OR
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegisterForm().setVisible(true);
//            }
//        });
         */
    }//end -main() method   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Register;
    private javax.swing.JCheckBox jCheckBox_ShowPassword;
    private javax.swing.JLabel jLabel_AlreadyLogin;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_ConfirmPassword;
    private javax.swing.JLabel jLabel_Fullname;
    private javax.swing.JLabel jLabel_Gender;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Petname;
    private javax.swing.JLabel jLabel_Phone;
    private javax.swing.JLabel jLabel_RegisterTitle;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JPasswordField jPasswordField_ConfirmPassword;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JTextField jTextField_Fullname;
    private javax.swing.JTextField jTextField_Petname;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables

}// end - RegisterForm class
